
application:
  weatherServiceBaseUrl: https://samples.openweathermap.org/data/2.5
  weatherServiceAppId: b6907d289e10d714a6e88b30761fae22

#feign:
#  client:
#    config:
#      weather-service:
#        remoteRuntimeService:
#          url: ${application.weatherServiceBaseUrl}
#        remoteRepositoryService:
#          url: ${application.weatherServiceBaseUrl}

